[package]
name = "lox-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
lox-shared = { path = "../lox-shared", version = "0.1.0" }
lox-ast = { path = "../lox-ast", version = "0.1.0" }

# External
bytes = { workspace = true }
hashbrown = { workspace = true }
