[package]
name = "lox-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
lox-shared = { path = "../lox-shared", version = "0.1.0" }
lox-interpreter = { path = "../lox-interpreter", version = "0.1.0" }

# External
hashbrown = { workspace = true }
